#!/bin/bash
# Script fix ESP32 boot mode issue

echo "🔧 Fix ESP32 Boot Mode Issue"
echo "============================"

echo "📋 Vấn đề:"
echo "A fatal error occurred: Failed to connect to ESP32: Wrong boot mode detected (0xb)!"
echo "The chip needs to be in download mode."

echo ""
echo "✅ Giải pháp:"

echo ""
echo "🔧 Phương pháp 1: Manual Boot Mode Reset"
echo "======================================"
echo "1. 🔌 Đảm bảo ESP32 được cắm vào USB"
echo "2. 🔄 Nhấn và giữ nút BOOT (GPIO0)"
echo "3. 🔄 Nhấn nút RESET (EN)"
echo "4. 🔄 Thả nút RESET trước"
echo "5. 🔄 Thả nút BOOT sau"
echo "6. 🚀 ESP32 sẽ vào download mode"

echo ""
echo "🔧 Phương pháp 2: Auto Boot Mode Reset"
echo "====================================="
echo "1. 🔌 Đảm bảo ESP32 được cắm vào USB"
echo "2. 🔄 Nhấn và giữ nút BOOT (GPIO0)"
echo "3. 🔄 Nhấn nút RESET (EN)"
echo "4. 🔄 Thả nút RESET trước"
echo "5. 🔄 Thả nút BOOT sau"
echo "6. 🚀 Chạy upload command ngay lập tức"

echo ""
echo "🔧 Phương pháp 3: Hardware Reset"
echo "==============================="
echo "1. 🔌 Tắt nguồn ESP32"
echo "2. 🔄 Nhấn và giữ nút BOOT (GPIO0)"
echo "3. 🔌 Bật nguồn ESP32"
echo "4. 🔄 Thả nút BOOT"
echo "5. 🚀 ESP32 sẽ vào download mode"

echo ""
echo "🔧 Phương pháp 4: Software Reset"
echo "==============================="
echo "1. 🔌 Đảm bảo ESP32 được cắm vào USB"
echo "2. 🔄 Nhấn và giữ nút BOOT (GPIO0)"
echo "3. 🔄 Nhấn nút RESET (EN)"
echo "4. 🔄 Thả nút RESET trước"
echo "5. 🔄 Thả nút BOOT sau"
echo "6. 🚀 Chạy upload command ngay lập tức"

echo ""
echo "🔧 Phương pháp 5: esptool Reset"
echo "=============================="
echo "1. 🔌 Đảm bảo ESP32 được cắm vào USB"
echo "2. 🔄 Chạy esptool reset:"
echo "   esptool.py --port /dev/ttyUSB0 run"
echo "3. 🚀 Chạy upload command ngay lập tức"

echo ""
echo "🔧 Phương pháp 6: PlatformIO Reset"
echo "================================="
echo "1. 🔌 Đảm bảo ESP32 được cắm vào USB"
echo "2. 🔄 Chạy PlatformIO reset:"
echo "   pio run -t upload -e esp32dev --upload-port /dev/ttyUSB0"
echo "3. 🚀 Nếu fail, thử lại với delay"

echo ""
echo "🔧 Phương pháp 7: Arduino IDE Reset"
echo "=================================="
echo "1. 🔌 Đảm bảo ESP32 được cắm vào USB"
echo "2. 🔄 Mở Arduino IDE"
echo "3. 🔄 Chọn Board: ESP32 Dev Module"
echo "4. 🔄 Chọn Port: /dev/ttyUSB0"
echo "5. 🔄 Nhấn Upload"
echo "6. 🚀 Nếu fail, thử lại với delay"

echo ""
echo "🔧 Phương pháp 8: esptool Direct Upload"
echo "======================================"
echo "1. 🔌 Đảm bảo ESP32 được cắm vào USB"
echo "2. 🔄 Reset ESP32 về download mode"
echo "3. 🔄 Chạy esptool direct upload:"
echo "   esptool.py --port /dev/ttyUSB0 --baud 115200 write_flash 0x10000 firmware.bin"
echo "4. 🚀 Nếu fail, thử lại với delay"

echo ""
echo "🔧 Phương pháp 9: esptool with Reset"
echo "==================================="
echo "1. 🔌 Đảm bảo ESP32 được cắm vào USB"
echo "2. 🔄 Chạy esptool với reset:"
echo "   esptool.py --port /dev/ttyUSB0 --baud 115200 --before default_reset --after hard_reset write_flash 0x10000 firmware.bin"
echo "3. 🚀 Nếu fail, thử lại với delay"

echo ""
echo "🔧 Phương pháp 10: esptool with Chip Reset"
echo "========================================="
echo "1. 🔌 Đảm bảo ESP32 được cắm vào USB"
echo "2. 🔄 Chạy esptool với chip reset:"
echo "   esptool.py --port /dev/ttyUSB0 --baud 115200 --before default_reset --after hard_reset --chip esp32 write_flash 0x10000 firmware.bin"
echo "3. 🚀 Nếu fail, thử lại với delay"

echo ""
echo "🚀 Cách sử dụng:"
echo "==============="
echo "1. 🔌 Đảm bảo ESP32 được cắm vào USB"
echo "2. 🔄 Reset ESP32 về download mode"
echo "3. 🚀 Chạy upload command ngay lập tức"
echo "4. 🔄 Nếu fail, thử lại với delay"

echo ""
echo "🔍 Troubleshooting:"
echo "=================="
echo "1. 🔌 Kiểm tra USB cable"
echo "2. 🔌 Kiểm tra USB port"
echo "3. 🔌 Kiểm tra ESP32 power"
echo "4. 🔌 Kiểm tra driver USB-Serial"
echo "5. 🔌 Kiểm tra permissions /dev/ttyUSB0"

echo ""
echo "🎯 Next Steps:"
echo "============="
echo "1. 🔄 Reset ESP32 về download mode"
echo "2. 🚀 Chạy upload command ngay lập tức"
echo "3. 🔄 Nếu fail, thử lại với delay"
echo "4. 🔍 Kiểm tra hardware nếu vẫn fail"
