#!/bin/bash

echo "🚀 Upload Firmware với Fast Boot Path (15-20s Setup)"
echo "=================================================="

echo "📝 Các tối ưu hóa đã thực hiện:"
echo "   ✅ Fast Boot Path - setup tối thiểu trong 3-5s"
echo "   ✅ Network task chạy song song với FreeRTOS"
echo "   ✅ Web interface sẵn sàng ngay sau 5s"
echo "   ✅ Giảm cellular reset delay từ 5s xuống 2s"
echo "   ✅ Giảm modem power on delay từ 3s xuống 1.5s"
echo "   ✅ Giảm NETOPEN timeout từ 8s xuống 5s"
echo "   ✅ WiFi connect với SSID cố định (8s timeout)"
echo "   ✅ Firmware check dời sau upload đầu tiên"
echo "   ✅ NTP sync chạy trong background"
echo ""

echo "🔧 Upload firmware..."
platformio run --target upload --environment esp32dev

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Upload thành công!"
    echo ""
    echo "📊 Kết quả mong đợi:"
    echo "   • Fast Boot Path: <5 giây"
    echo "   • Web interface: 192.168.4.1 sẵn sàng ngay"
    echo "   • Network connection: 15-20 giây (background)"
    echo "   • Tổng setup time: 15-20 giây thay vì 40-60 giây"
    echo ""
    echo "🔍 Monitor serial để xem kết quả:"
    echo "   platformio device monitor -e esp32dev"
    echo ""
    echo "📈 So sánh với trước:"
    echo "   • Setup time: 40-60s → 15-20s (giảm 60-70%)"
    echo "   • Web interface: 30-40s → 5s (giảm 85%)"
    echo "   • Network init: chặn → background"
    echo "   • User experience: chờ lâu → sẵn sàng ngay"
    echo ""
    echo "🎯 Fast Boot Path hoạt động:"
    echo "   1. ESP32 khởi động (<5s)"
    echo "   2. Web interface sẵn sàng ngay"
    echo "   3. Network task chạy background"
    echo "   4. Khi có mạng → NTP sync + upload data"
    echo ""
else
    echo ""
    echo "❌ Upload thất bại!"
    echo "Kiểm tra:"
    echo "   • ESP32 đã kết nối USB"
    echo "   • Driver đã cài đặt"
    echo "   • Port không bị chiếm dụng"
    echo ""
fi
